server:
  port: 9000

spring:
  application:
    name: business-service

  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      enabled: true
    config:
      server-addr: 127.0.0.1:8848
  main:
    allow-bean-definition-overriding: true

seata:
  enable-auto-data-source-proxy: false
  application-id: ${spring.application.name}
  tx-service-group: business-service-group
  service:
    vgroupMapping:
      business-service-group: default
    grouplist:
      default: 127.0.0.1:8091
  registry:
    type: nacos
    nacos.:
      server-addr: localhost:8848
      application: seata-server
      group: SEATA_GROUP
  config:
    type: nacos
    nacos.:
      server-addr: localhost:8848
      group: SEATA_GROUP