GET localhost:12002/chats/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzeXN0ZW0iOiJDdXN0b21lciBTeXN0ZW0iLCJ1c2VyX25hbWUiOiJhZG1pbiIsInNjb3BlIjpbIndlYmNsaWVudCJdLCJleHAiOjE2NzgxOTc0ODksImF1dGhvcml0aWVzIjpbIlJPTEVfQURNSU4iLCJST0xFX1VTRVIiXSwianRpIjoiZjhiYzM4MGEtM2MxYi00OTk0LWIwOWYtMWRlZTNlOWIzZjUyIiwiY2xpZW50X2lkIjoiY3NfY2xpZW50In0.d1vq2xp2pz5UlJ0VYmWH7_Trsn-ObFZFQBkVPq-64P0

###

GET localhost:12002/chats/
Content-Type: application/json

###

GET localhost:12002/chats/1
Content-Type: application/json

###

GET localhost:12002/chats/switch
Content-Type: application/json

###
